Origin/tarasenko catalog html
Natatulichka/DDT pull request #3
Opened 2024-03-22 01:07 UTC by HannaTarasenko

2024-03-22 08:50 UTC, Natatulichka requested changes
Приклад реалізації тегу  <picture>
                 <picture>
              <source srcset="./images/barbers/barber2-mobile.webp 1x, ./images/barbers/barber2-mobile@2x.webp 2x" media="(max-width:767px)" type="image/webp" />
              <source srcset="./images/barbers/barber2-mobile.jpg 1x, ./images/barbers/barber2-mobile@2x.jpg 2x" media="(max-width:767px)" type="image/jpeg" />
              
              <source srcset="./images/barbers/barber2-tablet.webp 1x, ./images/barbers/barber2-tablet@2x.webp 2x" media="(max-width:1199px)" type="image/webp" />
              <source srcset="./images/barbers/barber2-tablet.jpg 1x, ./images/barbers/barber2-tablet@2x.jpg 2x" media="(max-width:1199px)" type="image/jpeg" />
              
              <source srcset="./images/barbers/barber2-desctop.webp 1x, ./images/barbers/barber2-desctop@2x.webp 2x" media="(min-width:1200px)" type="image/webp" />
              <source srcset="./images/barbers/barber2-desctop.jpg 1x, ./images/barbers/barber2-desctop@2x.jpg 2x" media="(min-width:1200px)" type="image/jpeg" />
              
              <img src="./images/barbers/barber2-mobile.jpg" alt="John Smith" />
      </picture>
А в CSS вже прописуємо висоту й ширину.
Крапка ставиться одна - це пояснювали у відео "Старт проєкту, планування з ментором"
І згідна з Сергієм - формат jpeg та webp

2024-03-23 01:21 UTC, Natatulichka commented
деякі картинки не відкриваються (дивлюся в інструментах розробника)

2024-03-23 13:32 UTC, HannaTarasenko commented
Доброго дня ☺️ Могли б ви, будь ласка, уточнити, які саме картинки, я перевіряла через Network, усі відкривалися, х1 та х2.

2024-03-24 03:50 UTC, Natatulichka approved these changes

2024-03-24 03:50 UTC, merged