created html and css for header
Natatulichka/DDT pull request #6
Opened 2024-03-22 13:06 UTC by ITStupak

2024-03-22 14:21 UTC, Natatulichka requested changes
контейнерам ширину не задавай и в медиаправилах тоже . я пишу в резете

2024-03-22 15:57 UTC, ITStupak commented
так, за контейнери я вже побачив у файлі reset, коли писав тобі змінити width на max-width ;)

2024-03-22 18:32 UTC, Natatulichka requested changes
не видно іконок, посилання на кожну секцію #name-section, посилання на загальний спрайт

2024-03-23 01:39 UTC, Natatulichka commented
бургер не прорисоавлся, десктоп не по макету расстояния, таблет гап 32, лайн-хайт не верный

2024-03-23 17:58 UTC, ITStupak commented
Ок. Посмотрю и отпишусь тебе.
Странно, но бургер у меня в локальной версии был на месте😅 Впрочем как и gap в планшете был 32 а в мобилке 24.
По десктопу уточни какие расстояния надо поправить. И с line-height где именно?

2024-03-23 22:56 UTC, Natatulichka commented
![image](https://github.com/Natatulichka/DDT/assets/155992841/4d6699c8-d264-44ee-b733-129bdae09194)
Висота мобыльного меню на макеті не збігається там паддінг верхній від  Home 240
![image](https://github.com/Natatulichka/DDT/assets/155992841/bfc59b30-2fa5-4dd7-925f-82310e07ea2b)
![image](https://github.com/Natatulichka/DDT/assets/155992841/190bf7d7-2f95-4088-b07b-28d4132e1509)
Соц мережі не відцентрувалися
![image](https://github.com/Natatulichka/DDT/assets/155992841/5ca4142f-e76d-48af-8b11-6d41ce2c0ecd)
Постав fill для close-btn 
![image](https://github.com/Natatulichka/DDT/assets/155992841/6091afb7-7139-45de-9624-edcf4ddc19f2)
Нижній відступ від Home і псевдоелементом.

2024-03-24 00:31 UTC, ITStupak commented
Шось я не розумію чому в тебе такі питання, які в мене локально вирішені ...

По черзі:
1. "Висота мобыльного меню на макеті не збігається там паддінг верхній від Home 240" - 
немає в мобільного меню фіксованої висоти, бо висота підстраюється під viewport користувача, згідно тех.завданню: "Меню фіксоване, висота відповідає висоті в'юпорту."

Просто з тими padding що в макеті в мене виникає друге питання, навіщо стількі порожнього місця залишається, що навіть на ноуті не влізає одразу всі елементи (кнопка, меню та іконки соцмереж)... Може потрібно якось "резинити" цей простір між верхнім краєм та початком меню а також між кінцем меню та іконками...? Але як?

2. Верхній padding в мене прописаний і дорівнює 240px: 
![padding mobil menu](https://github.com/Natatulichka/DDT/assets/155536969/d7e94ee6-cd2f-4397-87f7-36aad81f37c6)

3. "Соц мережі не відцентрувалися" - в мене все ок. Дивись: 
![social icons](https://github.com/Natatulichka/DDT/assets/1555369
![Снимок экрана 2024-03-24 010035](https://github.com/Natatulichka/DDT/assets/155536969/717b68ca-9c81-4d8e-8c7e-90a0c67d1874)
69/5df9177a-0953-439c-b91b-ff54e2b6e7b0)

5. "Постав fill для close-btn"... По-перше, теж відображається в мене як повинно бути, ось: 
![close-btn mobil menu](https://github.com/Natatulichka/DDT/assets/155536969/8550715e-f10b-4617-ad73-95e8b9921962)
А по-друге, бургер та хрестик зроблені у спрайті за допомогою stroke, а не fill і в селекторі css для кнопки, stroke вказаний.

6. З бургером в мене також немаэ проблем з прорисовкою: 
![burger](https://github.com/Natatulichka/DDT/assets/155536969/4b544dec-f422-44f1-be1e-d806153aea6c)


Перевір будь ласка ще раз, може ти не той коміт видкривала?

2024-03-24 13:33 UTC, Natatulichka commented
Написала у особисті Slack

2024-03-26 02:47 UTC, closed without merging